server:
  port: ${NODE_PORT}

spring:

  application:
    name: ${NODE_NAME}

  profiles:
    active:
      - telegram
      - rabbitmq
      - postgres
      - openfeign
      - actuator

  config:
    import: configserver:${APPLICATION_PROTOCOL}://${CONFIG_HOST}:${CONFIG_PORT}